package com.fit2cloud.fks.model;

import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

public class CsProject implements Serializable {
    @ApiModelProperty("ID")
    private String id;

    @ApiModelProperty(value = "集群ID", required = true)
    private String accountId;

    @ApiModelProperty("工作空间ID")
    private String workspaceId;

    @ApiModelProperty("名称")
    private String name;

    @ApiModelProperty("展示名称")
    private String displayName;

    @ApiModelProperty("创建时间")
    private Long createTime;

    @ApiModelProperty("描述")
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cs_project
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_project.id
     *
     * @return the value of cs_project.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_project.id
     *
     * @param id the value for cs_project.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_project.account_id
     *
     * @return the value of cs_project.account_id
     *
     * @mbg.generated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_project.account_id
     *
     * @param accountId the value for cs_project.account_id
     *
     * @mbg.generated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_project.workspace_id
     *
     * @return the value of cs_project.workspace_id
     *
     * @mbg.generated
     */
    public String getWorkspaceId() {
        return workspaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_project.workspace_id
     *
     * @param workspaceId the value for cs_project.workspace_id
     *
     * @mbg.generated
     */
    public void setWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId == null ? null : workspaceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_project.name
     *
     * @return the value of cs_project.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_project.name
     *
     * @param name the value for cs_project.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_project.display_name
     *
     * @return the value of cs_project.display_name
     *
     * @mbg.generated
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_project.display_name
     *
     * @param displayName the value for cs_project.display_name
     *
     * @mbg.generated
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_project.create_time
     *
     * @return the value of cs_project.create_time
     *
     * @mbg.generated
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_project.create_time
     *
     * @param createTime the value for cs_project.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cs_project.description
     *
     * @return the value of cs_project.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cs_project.description
     *
     * @param description the value for cs_project.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}