package com.fit2cloud.fks.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;

public class KoSettings implements Serializable {
    @ApiModelProperty("")
    private Integer id;

    @ApiModelProperty("ko地址")
    private String koAddress;

    @ApiModelProperty("用户名")
    private String koAdmin;

    @ApiModelProperty("密码")
    private String adminPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ko_settings
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ko_settings.id
     *
     * @return the value of ko_settings.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ko_settings.id
     *
     * @param id the value for ko_settings.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ko_settings.ko_address
     *
     * @return the value of ko_settings.ko_address
     *
     * @mbg.generated
     */
    public String getKoAddress() {
        return koAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ko_settings.ko_address
     *
     * @param koAddress the value for ko_settings.ko_address
     *
     * @mbg.generated
     */
    public void setKoAddress(String koAddress) {
        this.koAddress = koAddress == null ? null : koAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ko_settings.ko_admin
     *
     * @return the value of ko_settings.ko_admin
     *
     * @mbg.generated
     */
    public String getKoAdmin() {
        return koAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ko_settings.ko_admin
     *
     * @param koAdmin the value for ko_settings.ko_admin
     *
     * @mbg.generated
     */
    public void setKoAdmin(String koAdmin) {
        this.koAdmin = koAdmin == null ? null : koAdmin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ko_settings.admin_password
     *
     * @return the value of ko_settings.admin_password
     *
     * @mbg.generated
     */
    public String getAdminPassword() {
        return adminPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ko_settings.admin_password
     *
     * @param adminPassword the value for ko_settings.admin_password
     *
     * @mbg.generated
     */
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword == null ? null : adminPassword.trim();
    }
}