package com.fit2cloud.fks.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;

public class YamlRepository implements Serializable {
    @ApiModelProperty("")
    private Integer id;

    @ApiModelProperty("仓库名称")
    private String name;

    @ApiModelProperty("仓库版本")
    private String version;

    @ApiModelProperty("用途描述")
    private String description;

    @ApiModelProperty("创建时间")
    private Date createTime;

    @ApiModelProperty("yaml文件")
    private byte[] yamlContent;

    @ApiModelProperty("集群ID")
    private String clusterId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yaml_repository
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaml_repository.id
     *
     * @return the value of yaml_repository.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaml_repository.id
     *
     * @param id the value for yaml_repository.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaml_repository.name
     *
     * @return the value of yaml_repository.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaml_repository.name
     *
     * @param name the value for yaml_repository.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaml_repository.description
     *
     * @return the value of yaml_repository.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaml_repository.description
     *
     * @param description the value for yaml_repository.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaml_repository.create_time
     *
     * @return the value of yaml_repository.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaml_repository.create_time
     *
     * @param createTime the value for yaml_repository.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public byte[] getYamlContent() {
        return yamlContent;
    }

    public void setYamlContent(byte[] yamlContent) {
        this.yamlContent = yamlContent;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getClusterId() {
        return clusterId;
    }

    public void setClusterId(String clusterId) {
        this.clusterId = clusterId;
    }
}