package com.fit2cloud.fks.model;

import io.swagger.annotations.ApiModelProperty;
import java.io.Serializable;
import java.util.Date;

public class YamlHistrory implements Serializable {
    @ApiModelProperty("")
    private Integer id;

    @ApiModelProperty("仓库id")
    private Integer repoId;

    @ApiModelProperty("仓库名称")
    private String repoName;

    @ApiModelProperty("集群id")
    private String clusterId;

    @ApiModelProperty("集群id")
    private String clusterName;

    @ApiModelProperty("master地址")
    private String masterUrl;

    @ApiModelProperty("token")
    private String token;

    @ApiModelProperty("创建时间")
    private Date createTime;

    @ApiModelProperty("完成时间")
    private Date finishTime;

    @ApiModelProperty("部署结果")
    private Boolean status;

    @ApiModelProperty("")
    private String message;

    @ApiModelProperty("yaml文件")
    private byte[] yamlFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yaml_histrory
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaml_histrory.id
     *
     * @return the value of yaml_histrory.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaml_histrory.id
     *
     * @param id the value for yaml_histrory.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaml_histrory.repo_id
     *
     * @return the value of yaml_histrory.repo_id
     *
     * @mbg.generated
     */
    public Integer getRepoId() {
        return repoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaml_histrory.repo_id
     *
     * @param repoId the value for yaml_histrory.repo_id
     *
     * @mbg.generated
     */
    public void setRepoId(Integer repoId) {
        this.repoId = repoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaml_histrory.repo_name
     *
     * @return the value of yaml_histrory.repo_name
     *
     * @mbg.generated
     */
    public String getRepoName() {
        return repoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaml_histrory.repo_name
     *
     * @param repoName the value for yaml_histrory.repo_name
     *
     * @mbg.generated
     */
    public void setRepoName(String repoName) {
        this.repoName = repoName == null ? null : repoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaml_histrory.cluster_id
     *
     * @return the value of yaml_histrory.cluster_id
     *
     * @mbg.generated
     */
    public String getClusterId() {
        return clusterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaml_histrory.cluster_id
     *
     * @param clusterId the value for yaml_histrory.cluster_id
     *
     * @mbg.generated
     */
    public void setClusterId(String clusterId) {
        this.clusterId = clusterId == null ? null : clusterId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaml_histrory.cluster_name
     *
     * @return the value of yaml_histrory.cluster_name
     *
     * @mbg.generated
     */
    public String getClusterName() {
        return clusterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaml_histrory.cluster_name
     *
     * @param clusterName the value for yaml_histrory.cluster_name
     *
     * @mbg.generated
     */
    public void setClusterName(String clusterName) {
        this.clusterName = clusterName == null ? null : clusterName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaml_histrory.master_url
     *
     * @return the value of yaml_histrory.master_url
     *
     * @mbg.generated
     */
    public String getMasterUrl() {
        return masterUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaml_histrory.master_url
     *
     * @param masterUrl the value for yaml_histrory.master_url
     *
     * @mbg.generated
     */
    public void setMasterUrl(String masterUrl) {
        this.masterUrl = masterUrl == null ? null : masterUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaml_histrory.token
     *
     * @return the value of yaml_histrory.token
     *
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaml_histrory.token
     *
     * @param token the value for yaml_histrory.token
     *
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaml_histrory.create_time
     *
     * @return the value of yaml_histrory.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaml_histrory.create_time
     *
     * @param createTime the value for yaml_histrory.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaml_histrory.finish_time
     *
     * @return the value of yaml_histrory.finish_time
     *
     * @mbg.generated
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaml_histrory.finish_time
     *
     * @param finishTime the value for yaml_histrory.finish_time
     *
     * @mbg.generated
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaml_histrory.status
     *
     * @return the value of yaml_histrory.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaml_histrory.status
     *
     * @param status the value for yaml_histrory.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaml_histrory.message
     *
     * @return the value of yaml_histrory.message
     *
     * @mbg.generated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaml_histrory.message
     *
     * @param message the value for yaml_histrory.message
     *
     * @mbg.generated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yaml_histrory.yaml_file
     *
     * @return the value of yaml_histrory.yaml_file
     *
     * @mbg.generated
     */
    public byte[] getYamlFile() {
        return yamlFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yaml_histrory.yaml_file
     *
     * @param yamlFile the value for yaml_histrory.yaml_file
     *
     * @mbg.generated
     */
    public void setYamlFile(byte[] yamlFile) {
        this.yamlFile = yamlFile;
    }
}