package com.fit2cloud.fks.dto;

import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

//public class ClusterProductWithBLOBs extends Product implements Serializable {
public class ProductWithBLOBs implements Serializable {
    @ApiModelProperty("启动参数")
    private String launchConfiguration;

    @ApiModelProperty("扩展字段")
    private String extendData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vm_product
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vm_product.launch_configuration
     *
     * @return the value of vm_product.launch_configuration
     *
     * @mbg.generated
     */
    public String getLaunchConfiguration() {
        return launchConfiguration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vm_product.launch_configuration
     *
     * @param launchConfiguration the value for vm_product.launch_configuration
     *
     * @mbg.generated
     */
    public void setLaunchConfiguration(String launchConfiguration) {
        this.launchConfiguration = launchConfiguration == null ? null : launchConfiguration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vm_product.extend_data
     *
     * @return the value of vm_product.extend_data
     *
     * @mbg.generated
     */
    public String getExtendData() {
        return extendData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vm_product.extend_data
     *
     * @param extendData the value for vm_product.extend_data
     *
     * @mbg.generated
     */
    public void setExtendData(String extendData) {
        this.extendData = extendData == null ? null : extendData.trim();
    }
}