package com.fit2cloud.fks.dao;

import com.fit2cloud.fks.model.CsProject;
import com.fit2cloud.fks.model.CsProjectExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CsProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_project
     *
     * @mbg.generated
     */
    long countByExample(CsProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_project
     *
     * @mbg.generated
     */
    int deleteByExample(CsProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_project
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_project
     *
     * @mbg.generated
     */
    int insert(CsProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_project
     *
     * @mbg.generated
     */
    int insertSelective(CsProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_project
     *
     * @mbg.generated
     */
    List<CsProject> selectByExampleWithBLOBs(CsProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_project
     *
     * @mbg.generated
     */
    List<CsProject> selectByExample(CsProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_project
     *
     * @mbg.generated
     */
    CsProject selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_project
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CsProject record, @Param("example") CsProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_project
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") CsProject record, @Param("example") CsProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_project
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CsProject record, @Param("example") CsProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_project
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CsProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_project
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CsProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cs_project
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CsProject record);
}