package com.fit2cloud.fks.dao;

import com.fit2cloud.fks.model.KoSettings;
import com.fit2cloud.fks.model.KoSettingsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KoSettingsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ko_settings
     *
     * @mbg.generated
     */
    long countByExample(KoSettingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ko_settings
     *
     * @mbg.generated
     */
    int deleteByExample(KoSettingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ko_settings
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ko_settings
     *
     * @mbg.generated
     */
    int insert(KoSettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ko_settings
     *
     * @mbg.generated
     */
    int insertSelective(KoSettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ko_settings
     *
     * @mbg.generated
     */
    List<KoSettings> selectByExample(KoSettingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ko_settings
     *
     * @mbg.generated
     */
    KoSettings selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ko_settings
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") KoSettings record, @Param("example") KoSettingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ko_settings
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") KoSettings record, @Param("example") KoSettingsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ko_settings
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KoSettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ko_settings
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KoSettings record);
}