package com.fit2cloud.fks.dao;

import com.fit2cloud.fks.model.YamlRepository;
import com.fit2cloud.fks.model.YamlRepositoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YamlRepositoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaml_repository
     *
     * @mbg.generated
     */
    long countByExample(YamlRepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaml_repository
     *
     * @mbg.generated
     */
    int deleteByExample(YamlRepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaml_repository
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaml_repository
     *
     * @mbg.generated
     */
    int insert(YamlRepository record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaml_repository
     *
     * @mbg.generated
     */
    int insertSelective(YamlRepository record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaml_repository
     *
     * @mbg.generated
     */
    List<YamlRepository> selectByExample(YamlRepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaml_repository
     *
     * @mbg.generated
     */
    YamlRepository selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaml_repository
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YamlRepository record, @Param("example") YamlRepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaml_repository
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YamlRepository record, @Param("example") YamlRepositoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaml_repository
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YamlRepository record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaml_repository
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YamlRepository record);
}