package com.fit2cloud.fks.dao;

import com.fit2cloud.fks.model.YamlHistrory;
import com.fit2cloud.fks.model.YamlHistroryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface YamlHistroryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaml_histrory
     *
     * @mbg.generated
     */
    long countByExample(YamlHistroryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaml_histrory
     *
     * @mbg.generated
     */
    int deleteByExample(YamlHistroryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaml_histrory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaml_histrory
     *
     * @mbg.generated
     */
    int insert(YamlHistrory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaml_histrory
     *
     * @mbg.generated
     */
    int insertSelective(YamlHistrory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaml_histrory
     *
     * @mbg.generated
     */
    List<YamlHistrory> selectByExampleWithBLOBs(YamlHistroryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaml_histrory
     *
     * @mbg.generated
     */
    List<YamlHistrory> selectByExample(YamlHistroryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaml_histrory
     *
     * @mbg.generated
     */
    YamlHistrory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaml_histrory
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") YamlHistrory record, @Param("example") YamlHistroryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaml_histrory
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") YamlHistrory record, @Param("example") YamlHistroryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaml_histrory
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") YamlHistrory record, @Param("example") YamlHistroryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaml_histrory
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YamlHistrory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaml_histrory
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(YamlHistrory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yaml_histrory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YamlHistrory record);
}